### ISSUE TITLE
Define v0 goal of research for external conversations in January

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#18]
## Description
Equity Delivery wants to deliver not only a living roadmap toward equity delivery for USDS, but also have a more informed approach from subject matter experts doing equity scoping in and outside government. Our team needs to clearly articulate the outcome and milestone for this work at large and the goal for the upcoming month.

### Acceptance Criteria
A goal for v0 research is provided for acceptance by the team prior to ReOps planning or drafting other artifacts.

## Tasks

- [ ] Define outcome for the quarter
- [ ] **Articulate goal for v0 research for review and acceptance by team** @AlexBornkesselUSDS 

## Project Artifacts

**Comment by AlexBornkesselUSDS** [comment]
Given where we are now, I sense we are already actively talking with equity implementers within and outside of gov't and are continuing to build out our network there. 

2 options for consideration - the second motivates me most:
- **Pot. Goal:** Connect with people to gain insight into best practices, strategies and resources available to help teach and develop equity fluent leaders and implementers at USDS. This includes learning how to teach about race, privilege and power dimensions in a way that is approachable, safe, and invites curiosity. 
- Pros: Helps inform and prioritize approach for achieving desired learning objectives in team content modules and tools, for developing courageous leaders at USDS. Could also be a form of market research, in case we may want to contract someone to expand, build upon training modules and such. 
- Cons: Does this broach too far into Talent's territory? 

- **Pot. Goal:** Connect with people impacted by USDS projects (eg., mothers, grantees, veterans, unhoused, etc. etc.) to gain their POV and insight in what meaningful participation looks like from people that don't work in the Federal government. 
- Pros: Helps inform insight into what good participation looks and feels like from a non-wonky perspective. Could help inform language used within the spectrum and questions it includes. Builds on conversations-to-date. Could use the 3 questions Celeste and I already created and plan for 30- to 45-minute sessions with people. Ties into and (could) build on 0-5's planned design sessions in Feb/March too. Curious if this could also be...an opp to demonstrate how a listening-session-done-well could actually work. 
- Cons: We don't have incentives (yet) and not sure constraints, 'who' to talk with and how.

**Comment by celestemespinoza** [comment]
Archiving this ticket. We can revisit desire for research based on continuity of team and priorities in April.
